;;; any.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl (cl:declaim (cl:optimize (cl:debug 0) (sb-c:store-coverage-data 0)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")
    (cl:defpackage "CL-PROTOBUFS.GOOGLE.PROTOBUF" (:use))))

(cl:in-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(proto:define-schema 'any
    :syntax :proto3
    :package "google.protobuf"))

;; Top-Level messages.
(proto:define-message any
    (:conc-name "")
  ;; Fields.
  (type-url  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "typeUrl"
  )
  (value  :index 2  :type proto:byte-vector :label (:optional) :typename "bytes" :json-name "value"
  ))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(cl:setf (cl:gethash #P"any.proto" proto-impl::*all-schemas*)
         (proto:find-schema 'any)))

(cl:export '(any
             any
             type-url
             value))
