;;; descriptor.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl (cl:declaim (cl:optimize (cl:debug 0) (sb-c:store-coverage-data 0)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")
    (cl:defpackage "CL-PROTOBUFS.GOOGLE.PROTOBUF" (:use))))

(cl:in-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(proto:define-schema 'descriptor
    :syntax :proto2
    :package "google.protobuf"))

;; Top-Level messages.
(proto:define-message file-descriptor-set
    (:conc-name "")
  ;; Fields.
  (file  :index 1  :type (proto:list-of file-descriptor-proto) :label (:repeated :list) :typename "FileDescriptorProto" :json-name "file"
  ))
(proto:define-message file-descriptor-proto
    (:conc-name "")
  ;; Fields.
  (name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "name"
  )
  (package  :index 2  :type cl:string :label (:optional) :typename "string" :json-name "package"
  )
  (dependency  :index 3  :type (proto:list-of cl:string) :label (:repeated :list) :typename "string" :json-name "dependency"
  )
  (public-dependency  :index 10  :type (proto:list-of proto:int32) :label (:repeated :list) :typename "int32" :json-name "publicDependency"
  )
  (weak-dependency  :index 11  :type (proto:list-of proto:int32) :label (:repeated :list) :typename "int32" :json-name "weakDependency"
  )
  (message-type  :index 4  :type (proto:list-of descriptor-proto) :label (:repeated :list) :typename "DescriptorProto" :json-name "messageType"
  )
  (enum-type  :index 5  :type (proto:list-of enum-descriptor-proto) :label (:repeated :list) :typename "EnumDescriptorProto" :json-name "enumType"
  )
  (service  :index 6  :type (proto:list-of service-descriptor-proto) :label (:repeated :list) :typename "ServiceDescriptorProto" :json-name "service"
  )
  (extension  :index 7  :type (proto:list-of field-descriptor-proto) :label (:repeated :list) :typename "FieldDescriptorProto" :json-name "extension"
  )
  (options  :index 8  :type (cl:or cl:null file-options) :label (:optional) :typename "FileOptions" :json-name "options"
  )
  (source-code-info  :index 9  :type (cl:or cl:null source-code-info) :label (:optional) :typename "SourceCodeInfo" :json-name "sourceCodeInfo"
  )
  (syntax  :index 12  :type cl:string :label (:optional) :typename "string" :json-name "syntax"
  ))
(proto:define-message descriptor-proto
    (:conc-name "")
  ;; Nested messages.
  (proto:define-message descriptor-proto.extension-range
      (:conc-name "")
    ;; Fields.
    (start  :index 1  :type proto:int32 :label (:optional) :typename "int32" :json-name "start"
    )
    (end  :index 2  :type proto:int32 :label (:optional) :typename "int32" :json-name "end"
    )
    (options  :index 3  :type (cl:or cl:null extension-range-options) :label (:optional) :typename "google.protobuf.ExtensionRangeOptions" :json-name "options"
    ))
  (proto:define-message descriptor-proto.reserved-range
      (:conc-name "")
    ;; Fields.
    (start  :index 1  :type proto:int32 :label (:optional) :typename "int32" :json-name "start"
    )
    (end  :index 2  :type proto:int32 :label (:optional) :typename "int32" :json-name "end"
    ))
  ;; Fields.
  (name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "name"
  )
  (field  :index 2  :type (proto:list-of field-descriptor-proto) :label (:repeated :list) :typename "FieldDescriptorProto" :json-name "field"
  )
  (extension  :index 6  :type (proto:list-of field-descriptor-proto) :label (:repeated :list) :typename "FieldDescriptorProto" :json-name "extension"
  )
  (nested-type  :index 3  :type (proto:list-of descriptor-proto) :label (:repeated :list) :typename "DescriptorProto" :json-name "nestedType"
  )
  (enum-type  :index 4  :type (proto:list-of enum-descriptor-proto) :label (:repeated :list) :typename "EnumDescriptorProto" :json-name "enumType"
  )
  (extension-range  :index 5  :type (proto:list-of descriptor-proto.extension-range) :label (:repeated :list) :typename "ExtensionRange" :json-name "extensionRange"
  )
  (oneof-decl  :index 8  :type (proto:list-of oneof-descriptor-proto) :label (:repeated :list) :typename "OneofDescriptorProto" :json-name "oneofDecl"
  )
  (options  :index 7  :type (cl:or cl:null message-options) :label (:optional) :typename "MessageOptions" :json-name "options"
  )
  (reserved-range  :index 9  :type (proto:list-of descriptor-proto.reserved-range) :label (:repeated :list) :typename "ReservedRange" :json-name "reservedRange"
  )
  (reserved-name  :index 10  :type (proto:list-of cl:string) :label (:repeated :list) :typename "string" :json-name "reservedName"
  ))
(proto:define-message extension-range-options
    (:conc-name "")
  ;; Fields.
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message field-descriptor-proto
    (:conc-name "")
  ;; Nested enums.
  (proto:define-enum field-descriptor-proto.type
      ()
    (type-double :index 1)
    (type-float :index 2)
    (type-int64 :index 3)
    (type-uint64 :index 4)
    (type-int32 :index 5)
    (type-fixed64 :index 6)
    (type-fixed32 :index 7)
    (type-bool :index 8)
    (type-string :index 9)
    (type-group :index 10)
    (type-message :index 11)
    (type-bytes :index 12)
    (type-uint32 :index 13)
    (type-enum :index 14)
    (type-sfixed32 :index 15)
    (type-sfixed64 :index 16)
    (type-sint32 :index 17)
    (type-sint64 :index 18))
  (proto:define-enum field-descriptor-proto.label
      ()
    (label-optional :index 1)
    (label-required :index 2)
    (label-repeated :index 3))
  ;; Fields.
  (name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "name"
  )
  (number  :index 3  :type proto:int32 :label (:optional) :typename "int32" :json-name "number"
  )
  (label  :index 4  :type field-descriptor-proto.label :label (:optional) :typename "Label" :json-name "label"
  )
  (type  :index 5  :type field-descriptor-proto.type :label (:optional) :typename "Type" :json-name "type"
  )
  (type-name  :index 6  :type cl:string :label (:optional) :typename "string" :json-name "typeName"
  )
  (extendee  :index 2  :type cl:string :label (:optional) :typename "string" :json-name "extendee"
  )
  (default-value  :index 7  :type cl:string :label (:optional) :typename "string" :json-name "defaultValue"
  )
  (oneof-index  :index 9  :type proto:int32 :label (:optional) :typename "int32" :json-name "oneofIndex"
  )
  (json-name  :index 10  :type cl:string :label (:optional) :typename "string" :json-name "jsonName"
  )
  (options  :index 8  :type (cl:or cl:null field-options) :label (:optional) :typename "FieldOptions" :json-name "options"
  )
  (proto3-optional  :index 17  :type cl:boolean :label (:optional) :typename "bool" :json-name "proto3Optional"
  ))
(proto:define-message oneof-descriptor-proto
    (:conc-name "")
  ;; Fields.
  (name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "name"
  )
  (options  :index 2  :type (cl:or cl:null oneof-options) :label (:optional) :typename "OneofOptions" :json-name "options"
  ))
(proto:define-message enum-descriptor-proto
    (:conc-name "")
  ;; Nested messages.
  (proto:define-message enum-descriptor-proto.enum-reserved-range
      (:conc-name "")
    ;; Fields.
    (start  :index 1  :type proto:int32 :label (:optional) :typename "int32" :json-name "start"
    )
    (end  :index 2  :type proto:int32 :label (:optional) :typename "int32" :json-name "end"
    ))
  ;; Fields.
  (name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "name"
  )
  (value  :index 2  :type (proto:list-of enum-value-descriptor-proto) :label (:repeated :list) :typename "EnumValueDescriptorProto" :json-name "value"
  )
  (options  :index 3  :type (cl:or cl:null enum-options) :label (:optional) :typename "EnumOptions" :json-name "options"
  )
  (reserved-range  :index 4  :type (proto:list-of enum-descriptor-proto.enum-reserved-range) :label (:repeated :list) :typename "EnumReservedRange" :json-name "reservedRange"
  )
  (reserved-name  :index 5  :type (proto:list-of cl:string) :label (:repeated :list) :typename "string" :json-name "reservedName"
  ))
(proto:define-message enum-value-descriptor-proto
    (:conc-name "")
  ;; Fields.
  (name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "name"
  )
  (number  :index 2  :type proto:int32 :label (:optional) :typename "int32" :json-name "number"
  )
  (options  :index 3  :type (cl:or cl:null enum-value-options) :label (:optional) :typename "EnumValueOptions" :json-name "options"
  ))
(proto:define-message service-descriptor-proto
    (:conc-name "")
  ;; Fields.
  (name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "name"
  )
  (method  :index 2  :type (proto:list-of method-descriptor-proto) :label (:repeated :list) :typename "MethodDescriptorProto" :json-name "method"
  )
  (options  :index 3  :type (cl:or cl:null service-options) :label (:optional) :typename "ServiceOptions" :json-name "options"
  ))
(proto:define-message method-descriptor-proto
    (:conc-name "")
  ;; Fields.
  (name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "name"
  )
  (input-type  :index 2  :type cl:string :label (:optional) :typename "string" :json-name "inputType"
  )
  (output-type  :index 3  :type cl:string :label (:optional) :typename "string" :json-name "outputType"
  )
  (options  :index 4  :type (cl:or cl:null method-options) :label (:optional) :typename "MethodOptions" :json-name "options"
  )
  (client-streaming  :index 5  :type cl:boolean :label (:optional) :typename "bool" :json-name "clientStreaming"
   :default cl:nil)
  (server-streaming  :index 6  :type cl:boolean :label (:optional) :typename "bool" :json-name "serverStreaming"
   :default cl:nil))
(proto:define-message file-options
    (:conc-name "")
  ;; Nested enums.
  (proto:define-enum file-options.optimize-mode
      ()
    (speed :index 1)
    (code-size :index 2)
    (lite-runtime :index 3))
  ;; Fields.
  (java-package  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "javaPackage"
  )
  (java-outer-classname  :index 8  :type cl:string :label (:optional) :typename "string" :json-name "javaOuterClassname"
  )
  (java-multiple-files  :index 10  :type cl:boolean :label (:optional) :typename "bool" :json-name "javaMultipleFiles"
   :default cl:nil)
  (java-generate-equals-and-hash  :index 20  :type cl:boolean :label (:optional) :typename "bool" :json-name "javaGenerateEqualsAndHash"
  )
  (java-string-check-utf8  :index 27  :type cl:boolean :label (:optional) :typename "bool" :json-name "javaStringCheckUtf8"
   :default cl:nil)
  (optimize-for  :index 9  :type file-options.optimize-mode :label (:optional) :typename "OptimizeMode" :json-name "optimizeFor"
   :default :speed)
  (go-package  :index 11  :type cl:string :label (:optional) :typename "string" :json-name "goPackage"
  )
  (cc-generic-services  :index 16  :type cl:boolean :label (:optional) :typename "bool" :json-name "ccGenericServices"
   :default cl:nil)
  (java-generic-services  :index 17  :type cl:boolean :label (:optional) :typename "bool" :json-name "javaGenericServices"
   :default cl:nil)
  (py-generic-services  :index 18  :type cl:boolean :label (:optional) :typename "bool" :json-name "pyGenericServices"
   :default cl:nil)
  (php-generic-services  :index 42  :type cl:boolean :label (:optional) :typename "bool" :json-name "phpGenericServices"
   :default cl:nil)
  (deprecated  :index 23  :type cl:boolean :label (:optional) :typename "bool" :json-name "deprecated"
   :default cl:nil)
  (cc-enable-arenas  :index 31  :type cl:boolean :label (:optional) :typename "bool" :json-name "ccEnableArenas"
   :default cl:t)
  (objc-class-prefix  :index 36  :type cl:string :label (:optional) :typename "string" :json-name "objcClassPrefix"
  )
  (csharp-namespace  :index 37  :type cl:string :label (:optional) :typename "string" :json-name "csharpNamespace"
  )
  (swift-prefix  :index 39  :type cl:string :label (:optional) :typename "string" :json-name "swiftPrefix"
  )
  (php-class-prefix  :index 40  :type cl:string :label (:optional) :typename "string" :json-name "phpClassPrefix"
  )
  (php-namespace  :index 41  :type cl:string :label (:optional) :typename "string" :json-name "phpNamespace"
  )
  (php-metadata-namespace  :index 44  :type cl:string :label (:optional) :typename "string" :json-name "phpMetadataNamespace"
  )
  (ruby-package  :index 45  :type cl:string :label (:optional) :typename "string" :json-name "rubyPackage"
  )
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message message-options
    (:conc-name "")
  ;; Fields.
  (message-set-wire-format  :index 1  :type cl:boolean :label (:optional) :typename "bool" :json-name "messageSetWireFormat"
   :default cl:nil)
  (no-standard-descriptor-accessor  :index 2  :type cl:boolean :label (:optional) :typename "bool" :json-name "noStandardDescriptorAccessor"
   :default cl:nil)
  (deprecated  :index 3  :type cl:boolean :label (:optional) :typename "bool" :json-name "deprecated"
   :default cl:nil)
  (map-entry  :index 7  :type cl:boolean :label (:optional) :typename "bool" :json-name "mapEntry"
  )
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message field-options
    (:conc-name "")
  ;; Nested enums.
  (proto:define-enum field-options.c-type
      ()
    (string :index 0)
    (cord :index 1)
    (string-piece :index 2))
  (proto:define-enum field-options.js-type
      (:name "JSType")
    (js-normal :index 0)
    (js-string :index 1)
    (js-number :index 2))
  ;; Fields.
  (ctype  :index 1  :type field-options.c-type :label (:optional) :typename "CType" :json-name "ctype"
   :default :string)
  (packed  :index 2  :type cl:boolean :label (:optional) :typename "bool" :json-name "packed"
  )
  (jstype  :index 6  :type field-options.js-type :label (:optional) :typename "JSType" :json-name "jstype"
   :default :js-normal)
  (lazy  :index 5  :type cl:boolean :label (:optional) :typename "bool" :json-name "lazy"
   :default cl:nil)
  (deprecated  :index 3  :type cl:boolean :label (:optional) :typename "bool" :json-name "deprecated"
   :default cl:nil)
  (weak  :index 10  :type cl:boolean :label (:optional) :typename "bool" :json-name "weak"
   :default cl:nil)
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message oneof-options
    (:conc-name "")
  ;; Fields.
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message enum-options
    (:conc-name "")
  ;; Fields.
  (allow-alias  :index 2  :type cl:boolean :label (:optional) :typename "bool" :json-name "allowAlias"
  )
  (deprecated  :index 3  :type cl:boolean :label (:optional) :typename "bool" :json-name "deprecated"
   :default cl:nil)
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message enum-value-options
    (:conc-name "")
  ;; Fields.
  (deprecated  :index 1  :type cl:boolean :label (:optional) :typename "bool" :json-name "deprecated"
   :default cl:nil)
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message service-options
    (:conc-name "")
  ;; Fields.
  (deprecated  :index 33  :type cl:boolean :label (:optional) :typename "bool" :json-name "deprecated"
   :default cl:nil)
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message method-options
    (:conc-name "")
  ;; Nested enums.
  (proto:define-enum method-options.idempotency-level
      ()
    (idempotency-unknown :index 0)
    (no-side-effects :index 1)
    (idempotent :index 2))
  ;; Fields.
  (deprecated  :index 33  :type cl:boolean :label (:optional) :typename "bool" :json-name "deprecated"
   :default cl:nil)
  (idempotency-level  :index 34  :type method-options.idempotency-level :label (:optional) :typename "IdempotencyLevel" :json-name "idempotencyLevel"
   :default :idempotency-unknown)
  (uninterpreted-option  :index 999  :type (proto:list-of uninterpreted-option) :label (:repeated :list) :typename "UninterpretedOption" :json-name "uninterpretedOption"
  )
  ;; Extension ranges.
  (proto:define-extension 1000 536870911))
(proto:define-message uninterpreted-option
    (:conc-name "")
  ;; Nested messages.
  (proto:define-message uninterpreted-option.name-part
      (:conc-name "")
    ;; Fields.
    (name-part  :index 1  :type cl:string :label (:required) :typename "string" :json-name "namePart"
    )
    (is-extension  :index 2  :type cl:boolean :label (:required) :typename "bool" :json-name "isExtension"
    ))
  ;; Fields.
  (name  :index 2  :type (proto:list-of uninterpreted-option.name-part) :label (:repeated :list) :typename "NamePart" :json-name "name"
  )
  (identifier-value  :index 3  :type cl:string :label (:optional) :typename "string" :json-name "identifierValue"
  )
  (positive-int-value  :index 4  :type proto:uint64 :label (:optional) :typename "uint64" :json-name "positiveIntValue"
  )
  (negative-int-value  :index 5  :type proto:int64 :label (:optional) :typename "int64" :json-name "negativeIntValue"
  )
  (double-value  :index 6  :type cl:double-float :label (:optional) :typename "double" :json-name "doubleValue"
  )
  (string-value  :index 7  :type proto:byte-vector :label (:optional) :typename "bytes" :json-name "stringValue"
  )
  (aggregate-value  :index 8  :type cl:string :label (:optional) :typename "string" :json-name "aggregateValue"
  ))
(proto:define-message source-code-info
    (:conc-name "")
  ;; Nested messages.
  (proto:define-message source-code-info.location
      (:conc-name "")
    ;; Fields.
    (path  :index 1  :type (proto:list-of proto:int32) :label (:repeated :list) :typename "int32" :json-name "path"
     :packed cl:t)
    (span  :index 2  :type (proto:list-of proto:int32) :label (:repeated :list) :typename "int32" :json-name "span"
     :packed cl:t)
    (leading-comments  :index 3  :type cl:string :label (:optional) :typename "string" :json-name "leadingComments"
    )
    (trailing-comments  :index 4  :type cl:string :label (:optional) :typename "string" :json-name "trailingComments"
    )
    (leading-detached-comments  :index 6  :type (proto:list-of cl:string) :label (:repeated :list) :typename "string" :json-name "leadingDetachedComments"
    ))
  ;; Fields.
  (location  :index 1  :type (proto:list-of source-code-info.location) :label (:repeated :list) :typename "Location" :json-name "location"
  ))
(proto:define-message generated-code-info
    (:conc-name "")
  ;; Nested messages.
  (proto:define-message generated-code-info.annotation
      (:conc-name "")
    ;; Fields.
    (path  :index 1  :type (proto:list-of proto:int32) :label (:repeated :list) :typename "int32" :json-name "path"
     :packed cl:t)
    (source-file  :index 2  :type cl:string :label (:optional) :typename "string" :json-name "sourceFile"
    )
    (begin  :index 3  :type proto:int32 :label (:optional) :typename "int32" :json-name "begin"
    )
    (end  :index 4  :type proto:int32 :label (:optional) :typename "int32" :json-name "end"
    ))
  ;; Fields.
  (annotation  :index 1  :type (proto:list-of generated-code-info.annotation) :label (:repeated :list) :typename "Annotation" :json-name "annotation"
  ))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(cl:setf (cl:gethash #P"descriptor.proto" proto-impl::*all-schemas*)
         (proto:find-schema 'descriptor)))

(cl:export '(descriptor
             file-descriptor-set
             file
             file-descriptor-proto
             name
             package
             dependency
             public-dependency
             weak-dependency
             message-type
             enum-type
             service
             extension
             options
             source-code-info
             syntax
             descriptor-proto.extension-range
             start
             end
             options
             descriptor-proto.reserved-range
             start
             end
             descriptor-proto
             name
             field
             extension
             nested-type
             enum-type
             extension-range
             oneof-decl
             options
             reserved-range
             reserved-name
             extension-range-options
             uninterpreted-option
             field-descriptor-proto.type
             field-descriptor-proto.type->numeral
             numeral->field-descriptor-proto.type
             field-descriptor-proto.label
             field-descriptor-proto.label->numeral
             numeral->field-descriptor-proto.label
             field-descriptor-proto
             name
             number
             label
             type
             type-name
             extendee
             default-value
             oneof-index
             json-name
             options
             proto3-optional
             oneof-descriptor-proto
             name
             options
             enum-descriptor-proto.enum-reserved-range
             start
             end
             enum-descriptor-proto
             name
             value
             options
             reserved-range
             reserved-name
             enum-value-descriptor-proto
             name
             number
             options
             service-descriptor-proto
             name
             method
             options
             method-descriptor-proto
             name
             input-type
             output-type
             options
             client-streaming
             server-streaming
             file-options.optimize-mode
             file-options.optimize-mode->numeral
             numeral->file-options.optimize-mode
             file-options
             java-package
             java-outer-classname
             java-multiple-files
             java-generate-equals-and-hash
             java-string-check-utf8
             optimize-for
             go-package
             cc-generic-services
             java-generic-services
             py-generic-services
             php-generic-services
             deprecated
             cc-enable-arenas
             objc-class-prefix
             csharp-namespace
             swift-prefix
             php-class-prefix
             php-namespace
             php-metadata-namespace
             ruby-package
             uninterpreted-option
             message-options
             message-set-wire-format
             no-standard-descriptor-accessor
             deprecated
             map-entry
             uninterpreted-option
             field-options.c-type
             field-options.c-type->numeral
             numeral->field-options.c-type
             field-options.js-type
             field-options.js-type->numeral
             numeral->field-options.js-type
             field-options
             ctype
             packed
             jstype
             lazy
             deprecated
             weak
             uninterpreted-option
             oneof-options
             uninterpreted-option
             enum-options
             allow-alias
             deprecated
             uninterpreted-option
             enum-value-options
             deprecated
             uninterpreted-option
             service-options
             deprecated
             uninterpreted-option
             method-options.idempotency-level
             method-options.idempotency-level->numeral
             numeral->method-options.idempotency-level
             method-options
             deprecated
             idempotency-level
             uninterpreted-option
             uninterpreted-option.name-part
             name-part
             is-extension
             uninterpreted-option
             name
             identifier-value
             positive-int-value
             negative-int-value
             double-value
             string-value
             aggregate-value
             source-code-info.location
             path
             span
             leading-comments
             trailing-comments
             leading-detached-comments
             source-code-info
             location
             generated-code-info.annotation
             path
             source-file
             begin
             end
             generated-code-info
             annotation))
