;;; duration.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl (cl:declaim (cl:optimize (cl:debug 0) (sb-c:store-coverage-data 0)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")
    (cl:defpackage "CL-PROTOBUFS.GOOGLE.PROTOBUF" (:use))))

(cl:in-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(proto:define-schema 'duration
    :syntax :proto3
    :package "google.protobuf"))

;; Top-Level messages.
(proto:define-message duration
    (:conc-name "")
  ;; Fields.
  (seconds  :index 1  :type proto:int64 :label (:optional) :typename "int64" :json-name "seconds"
  )
  (nanos  :index 2  :type proto:int32 :label (:optional) :typename "int32" :json-name "nanos"
  ))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(cl:setf (cl:gethash #P"duration.proto" proto-impl::*all-schemas*)
         (proto:find-schema 'duration)))

(cl:export '(duration
             duration
             seconds
             nanos))
