;;; field_mask.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl (cl:declaim (cl:optimize (cl:debug 0) (sb-c:store-coverage-data 0)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")
    (cl:defpackage "CL-PROTOBUFS.GOOGLE.PROTOBUF" (:use))))

(cl:in-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(proto:define-schema 'field_mask
    :syntax :proto3
    :package "google.protobuf"))

;; Top-Level messages.
(proto:define-message field-mask
    (:conc-name "")
  ;; Fields.
  (paths  :index 1  :type (proto:list-of cl:string) :label (:repeated :list) :typename "string" :json-name "paths"
  ))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(cl:setf (cl:gethash #P"field_mask.proto" proto-impl::*all-schemas*)
         (proto:find-schema 'field_mask)))

(cl:export '(field_mask
             field-mask
             paths))
