;;; source_context.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl (cl:declaim (cl:optimize (cl:debug 0) (sb-c:store-coverage-data 0)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")
    (cl:defpackage "CL-PROTOBUFS.GOOGLE.PROTOBUF" (:use))))

(cl:in-package "CL-PROTOBUFS.GOOGLE.PROTOBUF")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(proto:define-schema 'source_context
    :syntax :proto3
    :package "google.protobuf"))

;; Top-Level messages.
(proto:define-message source-context
    (:conc-name "")
  ;; Fields.
  (file-name  :index 1  :type cl:string :label (:optional) :typename "string" :json-name "fileName"
  ))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(cl:setf (cl:gethash #P"source_context.proto" proto-impl::*all-schemas*)
         (proto:find-schema 'source_context)))

(cl:export '(source_context
             source-context
             file-name))
